// <auto-generated />
#if DEMO_APP
using System;
using System.IO;
using System.Runtime.CompilerServices;
using Salmon.Levels;
using Salmon.Levels.Enums;
using Salmon.Levels.Objects;

namespace Salmon;

internal static partial class GeneratedDynamicSerializers
{
    static GeneratedDynamicSerializers()
    {
        Register(typeof(ObjectReferences), static (value, writer) => WriteSalmon_Levels_Objects_ObjectReferences((ObjectReferences)value, writer), static reader => ReadSalmon_Levels_Objects_ObjectReferences(reader));
        Register(typeof(SettingsDefinition), static (value, writer) => WriteSalmon_Levels_Objects_SettingsDefinition((SettingsDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_SettingsDefinition(reader));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_ObjectReferences(ObjectReferences value, BinaryWriter writer)
    {
        writer.Write(0u);

        writer.Write(true);
        var specialLengthPosition = writer.BaseStream.Position;
        writer.Write(0u);
        var specialStart = writer.BaseStream.Position;
        ((ISpecialSerializable)value).SpecialWrite(writer);
        var specialEnd = writer.BaseStream.Position;
        writer.BaseStream.Position = specialLengthPosition;
        writer.Write(checked((uint)(specialEnd - specialStart)));
        writer.BaseStream.Position = specialEnd;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ObjectReferences ReadSalmon_Levels_Objects_ObjectReferences(BinaryReader reader)
    {
        var value = new ObjectReferences();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.ObjectReferences has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            ((ISpecialSerializable)value).SpecialRead(reader);
            if (reader.BaseStream.Position != specialEnd)
            {
                Debug.LogWarning($"Special read on Salmon.Levels.Objects.ObjectReferences has length {specialLength} but read {reader.BaseStream.Position - (specialEnd - specialLength)} bytes.");
            }
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_SettingsDefinition(SettingsDefinition value, BinaryWriter writer)
    {
        writer.Write(23u);

        WriteBooleanField(writer, -1.0f, value.AutoSave);

        WriteSingleField(writer, 1.0f, Clamp(value.GridSize, 0.02f, 10.0f));

        WriteSingleField(writer, 2.0f, Clamp(value.RotationSnapDegrees, 1.0f, 90.0f));

        WriteVector3Field(writer, 3.0f, value.CameraPosition);

        WriteSingleField(writer, 4.0f, value.CameraPitch);

        WriteSingleField(writer, 4.1f, value.CameraYaw);

        WriteBooleanField(writer, 4.3f, value.ObjectsSpawnAtOrigin);

        WriteStringField(writer, 5.0f, value.Material);

        WriteStringField(writer, 6.0f, value.BackgroundType);

        WriteSingleField(writer, 7.1f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 7.2f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 7.3f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteInt32Field(writer, 8.5f, Clamp(value.FogIntensity, 0.0f, 20.0f));

        WriteBooleanField(writer, 8.6f, value.PreviewMode);

        WriteSingleField(writer, 9.0f, Clamp(value.DeathY, -1000.0f, 1000.0f));

        WriteBooleanField(writer, 9.1f, value.DisplayStyle);

        WriteBooleanField(writer, 9.2f, value.AllowWalls);

        WriteBooleanField(writer, 9.3f, value.AllowCoyote);

        WriteBooleanField(writer, 10.0f, value.PreviewGuide);

        WriteBooleanField(writer, 11.0f, value.PreviewStart);

        WriteVector3Field(writer, 12.0f, value.PreviewPosition);

        WriteSingleField(writer, 13.0f, value.PreviewPitch);

        WriteSingleField(writer, 14.0f, value.PreviewYaw);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SettingsDefinition ReadSalmon_Levels_Objects_SettingsDefinition(BinaryReader reader)
    {
        var value = new SettingsDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -2.0f:
                    value.Title = reader.ReadString();
                    break;
                case -1.0f:
                    value.AutoSave = reader.ReadBoolean();
                    break;
                case 1.0f:
                    value.GridSize = Clamp(reader.ReadSingle(), 0.02f, 10.0f);
                    break;
                case 2.0f:
                    value.RotationSnapDegrees = Clamp(reader.ReadSingle(), 1.0f, 90.0f);
                    break;
                case 3.0f:
                    value.CameraPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 4.0f:
                    value.CameraPitch = reader.ReadSingle();
                    break;
                case 4.1f:
                    value.CameraYaw = reader.ReadSingle();
                    break;
                case 4.3f:
                    value.ObjectsSpawnAtOrigin = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.Material = reader.ReadString();
                    break;
                case 6.0f:
                    value.BackgroundType = reader.ReadString();
                    break;
                case 7.1f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.2f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.3f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 8.5f:
                    value.FogIntensity = Clamp(reader.ReadInt32(), 0.0f, 20.0f);
                    break;
                case 8.6f:
                    value.PreviewMode = reader.ReadBoolean();
                    break;
                case 9.0f:
                    value.DeathY = Clamp(reader.ReadSingle(), -1000.0f, 1000.0f);
                    break;
                case 9.1f:
                    value.DisplayStyle = reader.ReadBoolean();
                    break;
                case 9.2f:
                    value.AllowWalls = reader.ReadBoolean();
                    break;
                case 9.3f:
                    value.AllowCoyote = reader.ReadBoolean();
                    break;
                case 10.0f:
                    value.PreviewGuide = reader.ReadBoolean();
                    break;
                case 11.0f:
                    value.PreviewStart = reader.ReadBoolean();
                    break;
                case 12.0f:
                    value.PreviewPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 13.0f:
                    value.PreviewPitch = reader.ReadSingle();
                    break;
                case 14.0f:
                    value.PreviewYaw = reader.ReadSingle();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.SettingsDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }


}
#else
using System;
using System.IO;
using System.Runtime.CompilerServices;
using Salmon.Levels;
using Salmon.Levels.Enums;
using Salmon.Levels.Objects;

namespace Salmon;

internal static partial class GeneratedDynamicSerializers
{
    static GeneratedDynamicSerializers()
    {
        Register(typeof(Builtin), static (value, writer) => WriteSalmon_Levels_Objects_Builtin((Builtin)value, writer), static reader => ReadSalmon_Levels_Objects_Builtin(reader));
        Register(typeof(CheckpointObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_CheckpointObjectDefinition((CheckpointObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_CheckpointObjectDefinition(reader));
        Register(typeof(CoinObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_CoinObjectDefinition((CoinObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_CoinObjectDefinition(reader));
        Register(typeof(CounterTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_CounterTriggerObjectDefinition((CounterTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_CounterTriggerObjectDefinition(reader));
        Register(typeof(DeathTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_DeathTriggerObjectDefinition((DeathTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_DeathTriggerObjectDefinition(reader));
        Register(typeof(DelayTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_DelayTriggerObjectDefinition((DelayTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_DelayTriggerObjectDefinition(reader));
        Register(typeof(DestroyTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_DestroyTriggerObjectDefinition((DestroyTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_DestroyTriggerObjectDefinition(reader));
        Register(typeof(FollowTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_FollowTriggerObjectDefinition((FollowTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_FollowTriggerObjectDefinition(reader));
        Register(typeof(Group), static (value, writer) => WriteSalmon_Levels_Objects_Group((Group)value, writer), static reader => ReadSalmon_Levels_Objects_Group(reader));
        Register(typeof(IfTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_IfTriggerObjectDefinition((IfTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_IfTriggerObjectDefinition(reader));
        Register(typeof(LightObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_LightObjectDefinition((LightObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_LightObjectDefinition(reader));
        Register(typeof(MagnetFieldObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_MagnetFieldObjectDefinition((MagnetFieldObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_MagnetFieldObjectDefinition(reader));
        Register(typeof(MagnetPointObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_MagnetPointObjectDefinition((MagnetPointObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_MagnetPointObjectDefinition(reader));
        Register(typeof(MoveTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_MoveTriggerObjectDefinition((MoveTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_MoveTriggerObjectDefinition(reader));
        Register(typeof(ObjectReferences), static (value, writer) => WriteSalmon_Levels_Objects_ObjectReferences((ObjectReferences)value, writer), static reader => ReadSalmon_Levels_Objects_ObjectReferences(reader));
        Register(typeof(RandomTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_RandomTriggerObjectDefinition((RandomTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_RandomTriggerObjectDefinition(reader));
        Register(typeof(RotationTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_RotationTriggerObjectDefinition((RotationTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_RotationTriggerObjectDefinition(reader));
        Register(typeof(SetMaterialTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_SetMaterialTriggerObjectDefinition((SetMaterialTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_SetMaterialTriggerObjectDefinition(reader));
        Register(typeof(SettingsDefinition), static (value, writer) => WriteSalmon_Levels_Objects_SettingsDefinition((SettingsDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_SettingsDefinition(reader));
        Register(typeof(SkyColourTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_SkyColourTriggerObjectDefinition((SkyColourTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_SkyColourTriggerObjectDefinition(reader));
        Register(typeof(TeleportTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_TeleportTriggerObjectDefinition((TeleportTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_TeleportTriggerObjectDefinition(reader));
        Register(typeof(TextObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_TextObjectDefinition((TextObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_TextObjectDefinition(reader));
        Register(typeof(ToggleTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_ToggleTriggerObjectDefinition((ToggleTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_ToggleTriggerObjectDefinition(reader));
        Register(typeof(TouchTriggerObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_TouchTriggerObjectDefinition((TouchTriggerObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_TouchTriggerObjectDefinition(reader));
        Register(typeof(Wall), static (value, writer) => WriteSalmon_Levels_Objects_Wall((Wall)value, writer), static reader => ReadSalmon_Levels_Objects_Wall(reader));
        Register(typeof(WinObjectDefinition), static (value, writer) => WriteSalmon_Levels_Objects_WinObjectDefinition((WinObjectDefinition)value, writer), static reader => ReadSalmon_Levels_Objects_WinObjectDefinition(reader));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_Builtin(Builtin value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, 3.0f, value.Target);

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static Builtin ReadSalmon_Levels_Objects_Builtin(BinaryReader reader)
    {
        var value = new Builtin();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Target = reader.ReadString();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.Builtin has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_CheckpointObjectDefinition(CheckpointObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteByteField(writer, 3.0f, (byte)value.Direction);

        WriteBooleanField(writer, 4.0f, value.Visible);

        WriteBooleanField(writer, 4.5f, value.Audible);

        WriteObjectReferencesField(writer, 6.0f, value.Trigger);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CheckpointObjectDefinition ReadSalmon_Levels_Objects_CheckpointObjectDefinition(BinaryReader reader)
    {
        var value = new CheckpointObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Direction = (CardinalDirection)reader.ReadByte();
                    break;
                case 4.0f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 4.5f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 6.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.CheckpointObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_CoinObjectDefinition(CoinObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(8u);

        WriteBooleanField(writer, 2.5f, value.Visible);

        WriteBooleanField(writer, 2.6f, value.Audible);

        WriteObjectReferencesField(writer, 4.0f, value.OnPickup);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CoinObjectDefinition ReadSalmon_Levels_Objects_CoinObjectDefinition(BinaryReader reader)
    {
        var value = new CoinObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 2.5f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 2.6f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 4.0f:
                    value.OnPickup = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.CoinObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_CounterTriggerObjectDefinition(CounterTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteStringField(writer, 3.0f, value.Counter);

        WriteInt32Field(writer, 4.0f, value.CounterID);

        WriteByteField(writer, 5.0f, (byte)value.Operator);

        WriteStringField(writer, 6.0f, value.Operand);

        writer.Write(7.0f);
        var lengthPosition4 = writer.BaseStream.Position;
        writer.Write(0u);
        var valueStart4 = writer.BaseStream.Position;
        DynamicSerializer.WriteValue(writer, typeof(int[]), value.CounterIDs);
        var valueEnd4 = writer.BaseStream.Position;
        writer.BaseStream.Position = lengthPosition4;
        writer.Write(checked((uint)(valueEnd4 - valueStart4)));
        writer.BaseStream.Position = valueEnd4;

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CounterTriggerObjectDefinition ReadSalmon_Levels_Objects_CounterTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new CounterTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.Counter = reader.ReadString();
                    break;
                case 4.0f:
                    value.CounterID = reader.ReadInt32();
                    break;
                case 5.0f:
                    value.Operator = (Operator)reader.ReadByte();
                    break;
                case 6.0f:
                    value.Operand = reader.ReadString();
                    break;
                case 7.0f:
                    value.CounterIDs = (int[])DynamicSerializer.ReadValue(reader, typeof(int[]));
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.CounterTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_DeathTriggerObjectDefinition(DeathTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(3u);

        WriteObjectReferencesField(writer, 3.0f, value.OnRespawn);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DeathTriggerObjectDefinition ReadSalmon_Levels_Objects_DeathTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DeathTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.OnRespawn = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.DeathTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_DelayTriggerObjectDefinition(DelayTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteObjectReferencesField(writer, 3.5f, value.Trigger);

        WriteSingleField(writer, 4.0f, Clamp(value.Wait, 0.0f, 999.0f));

        WriteBooleanField(writer, 5.0f, value.RunOnStart);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DelayTriggerObjectDefinition ReadSalmon_Levels_Objects_DelayTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DelayTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.5f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Wait = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.0f:
                    value.RunOnStart = reader.ReadBoolean();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.DelayTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_DestroyTriggerObjectDefinition(DestroyTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(4u);

        WriteObjectReferencesField(writer, 3.5f, value.Destroy);

        WriteSingleField(writer, 6.0f, Clamp(value.Wait, 0.0f, 999.0f));

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DestroyTriggerObjectDefinition ReadSalmon_Levels_Objects_DestroyTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DestroyTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.5f:
                    value.Destroy = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 6.0f:
                    value.Wait = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.DestroyTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_FollowTriggerObjectDefinition(FollowTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteByteField(writer, 3.0f, (byte)value.FollowTarget);

        WriteSingleField(writer, 4.0f, Clamp(value.FollowRate, 0.0f, 1000.0f));

        WriteBooleanField(writer, 4.5f, value.Snap);

        WriteObjectReferencesField(writer, 5.0f, value.Follow);

        WriteBooleanField(writer, 6.0f, value.RunOnStart);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static FollowTriggerObjectDefinition ReadSalmon_Levels_Objects_FollowTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new FollowTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.FollowTarget = (FollowTarget)reader.ReadByte();
                    break;
                case 4.0f:
                    value.FollowRate = Clamp(reader.ReadSingle(), 0.0f, 1000.0f);
                    break;
                case 4.5f:
                    value.Snap = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.Follow = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 6.0f:
                    value.RunOnStart = reader.ReadBoolean();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.FollowTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_Group(Group value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(true);
        var specialLengthPosition = writer.BaseStream.Position;
        writer.Write(0u);
        var specialStart = writer.BaseStream.Position;
        ((ISpecialSerializable)value).SpecialWrite(writer);
        var specialEnd = writer.BaseStream.Position;
        writer.BaseStream.Position = specialLengthPosition;
        writer.Write(checked((uint)(specialEnd - specialStart)));
        writer.BaseStream.Position = specialEnd;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static Group ReadSalmon_Levels_Objects_Group(BinaryReader reader)
    {
        var value = new Group();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.Group has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            ((ISpecialSerializable)value).SpecialRead(reader);
            if (reader.BaseStream.Position != specialEnd)
            {
                Debug.LogWarning($"Special read on Salmon.Levels.Objects.Group has length {specialLength} but read {reader.BaseStream.Position - (specialEnd - specialLength)} bytes.");
            }
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_IfTriggerObjectDefinition(IfTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, 3.5f, value.Expression);

        writer.Write(4.5f);
        var lengthPosition1 = writer.BaseStream.Position;
        writer.Write(0u);
        var valueStart1 = writer.BaseStream.Position;
        DynamicSerializer.WriteValue(writer, typeof(int[]), value.CounterIDs);
        var valueEnd1 = writer.BaseStream.Position;
        writer.BaseStream.Position = lengthPosition1;
        writer.Write(checked((uint)(valueEnd1 - valueStart1)));
        writer.BaseStream.Position = valueEnd1;

        WriteObjectReferencesField(writer, 8.0f, value.TrueTrigger);

        WriteObjectReferencesField(writer, 9.0f, value.FalseTrigger);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static IfTriggerObjectDefinition ReadSalmon_Levels_Objects_IfTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new IfTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.Counter = reader.ReadString();
                    break;
                case 3.5f:
                    value.Expression = reader.ReadString();
                    break;
                case 4.0f:
                    value.Operand = reader.ReadInt32();
                    break;
                case 4.5f:
                    value.CounterIDs = (int[])DynamicSerializer.ReadValue(reader, typeof(int[]));
                    break;
                case 5.0f:
                    value.Operator = (Comparison)reader.ReadByte();
                    break;
                case 8.0f:
                    value.TrueTrigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 9.0f:
                    value.FalseTrigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.IfTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_LightObjectDefinition(LightObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteSingleField(writer, 3.0f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 5.0f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteSingleField(writer, 6.0f, Clamp(value.Intensity, 0.0f, 999.0f));

        WriteSingleField(writer, 7.0f, Clamp(value.Radius, 0.0f, 99.0f));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static LightObjectDefinition ReadSalmon_Levels_Objects_LightObjectDefinition(BinaryReader reader)
    {
        var value = new LightObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 6.0f:
                    value.Intensity = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 7.0f:
                    value.Radius = Clamp(reader.ReadSingle(), 0.0f, 99.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.LightObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_MagnetFieldObjectDefinition(MagnetFieldObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteSingleField(writer, 3.0f, Clamp(value.Strength, -999.0f, 999.0f));

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MagnetFieldObjectDefinition ReadSalmon_Levels_Objects_MagnetFieldObjectDefinition(BinaryReader reader)
    {
        var value = new MagnetFieldObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Strength = Clamp(reader.ReadSingle(), -999.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.MagnetFieldObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_MagnetPointObjectDefinition(MagnetPointObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteSingleField(writer, 3.0f, Clamp(value.Strength, -999.0f, 999.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Radius, 0.0f, 999.0f));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MagnetPointObjectDefinition ReadSalmon_Levels_Objects_MagnetPointObjectDefinition(BinaryReader reader)
    {
        var value = new MagnetPointObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Strength = Clamp(reader.ReadSingle(), -999.0f, 999.0f);
                    break;
                case 4.0f:
                    value.Radius = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.MagnetPointObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_MoveTriggerObjectDefinition(MoveTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(10u);

        WriteObjectReferencesField(writer, 3.5f, value.Move);

        WriteByteField(writer, 4.0f, (byte)value.MoveSpeedMode);

        WriteSingleField(writer, 5.0f, Clamp(value.MoveSpeed, 0.0f, 999.0f));

        WriteInt32Field(writer, 5.5f, (int)value.EasingType);

        WriteInt32Field(writer, 5.6f, (int)value.EasingDirection);

        WriteObjectReferencesField(writer, 7.0f, value.Trigger);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MoveTriggerObjectDefinition ReadSalmon_Levels_Objects_MoveTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new MoveTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.5f:
                    value.Move = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.MoveSpeedMode = (TriggerSpeedMode)reader.ReadByte();
                    break;
                case 5.0f:
                    value.MoveSpeed = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.5f:
                    value.EasingType = (EasingType)reader.ReadInt32();
                    break;
                case 5.6f:
                    value.EasingDirection = (EasingDirection)reader.ReadInt32();
                    break;
                case 7.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.MoveTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_ObjectReferences(ObjectReferences value, BinaryWriter writer)
    {
        writer.Write(0u);

        writer.Write(true);
        var specialLengthPosition = writer.BaseStream.Position;
        writer.Write(0u);
        var specialStart = writer.BaseStream.Position;
        ((ISpecialSerializable)value).SpecialWrite(writer);
        var specialEnd = writer.BaseStream.Position;
        writer.BaseStream.Position = specialLengthPosition;
        writer.Write(checked((uint)(specialEnd - specialStart)));
        writer.BaseStream.Position = specialEnd;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ObjectReferences ReadSalmon_Levels_Objects_ObjectReferences(BinaryReader reader)
    {
        var value = new ObjectReferences();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.ObjectReferences has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            ((ISpecialSerializable)value).SpecialRead(reader);
            if (reader.BaseStream.Position != specialEnd)
            {
                Debug.LogWarning($"Special read on Salmon.Levels.Objects.ObjectReferences has length {specialLength} but read {reader.BaseStream.Position - (specialEnd - specialLength)} bytes.");
            }
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_RandomTriggerObjectDefinition(RandomTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(3u);

        WriteObjectReferencesField(writer, 3.5f, value.Trigger);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static RandomTriggerObjectDefinition ReadSalmon_Levels_Objects_RandomTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new RandomTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.5f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.RandomTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_RotationTriggerObjectDefinition(RotationTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(10u);

        WriteObjectReferencesField(writer, 3.5f, value.Rotate);

        WriteByteField(writer, 4.0f, (byte)value.RotationSpeedMode);

        WriteSingleField(writer, 5.0f, Clamp(value.RotationSpeed, 0.0f, 999.0f));

        WriteInt32Field(writer, 5.5f, (int)value.EasingType);

        WriteInt32Field(writer, 5.6f, (int)value.EasingDirection);

        WriteObjectReferencesField(writer, 7.0f, value.Trigger);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static RotationTriggerObjectDefinition ReadSalmon_Levels_Objects_RotationTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new RotationTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.5f:
                    value.Rotate = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.RotationSpeedMode = (TriggerSpeedMode)reader.ReadByte();
                    break;
                case 5.0f:
                    value.RotationSpeed = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.5f:
                    value.EasingType = (EasingType)reader.ReadInt32();
                    break;
                case 5.6f:
                    value.EasingDirection = (EasingDirection)reader.ReadInt32();
                    break;
                case 7.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.RotationTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_SetMaterialTriggerObjectDefinition(SetMaterialTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(4u);

        WriteStringField(writer, 3.0f, value.Material);

        WriteObjectReferencesField(writer, 5.0f, value.Wall);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SetMaterialTriggerObjectDefinition ReadSalmon_Levels_Objects_SetMaterialTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new SetMaterialTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.Material = reader.ReadString();
                    break;
                case 5.0f:
                    value.Wall = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.SetMaterialTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_SettingsDefinition(SettingsDefinition value, BinaryWriter writer)
    {
        writer.Write(23u);

        WriteBooleanField(writer, -1.0f, value.AutoSave);

        WriteSingleField(writer, 1.0f, Clamp(value.GridSize, 0.02f, 10.0f));

        WriteSingleField(writer, 2.0f, Clamp(value.RotationSnapDegrees, 1.0f, 90.0f));

        WriteVector3Field(writer, 3.0f, value.CameraPosition);

        WriteSingleField(writer, 4.0f, value.CameraPitch);

        WriteSingleField(writer, 4.1f, value.CameraYaw);

        WriteBooleanField(writer, 4.3f, value.ObjectsSpawnAtOrigin);

        WriteStringField(writer, 5.0f, value.Material);

        WriteStringField(writer, 6.0f, value.BackgroundType);

        WriteSingleField(writer, 7.1f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 7.2f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 7.3f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteInt32Field(writer, 8.5f, Clamp(value.FogIntensity, 0.0f, 20.0f));

        WriteBooleanField(writer, 8.6f, value.PreviewMode);

        WriteSingleField(writer, 9.0f, Clamp(value.DeathY, -1000.0f, 1000.0f));

        WriteBooleanField(writer, 9.1f, value.DisplayStyle);

        WriteBooleanField(writer, 9.2f, value.AllowWalls);

        WriteBooleanField(writer, 9.3f, value.AllowCoyote);

        WriteBooleanField(writer, 10.0f, value.PreviewGuide);

        WriteBooleanField(writer, 11.0f, value.PreviewStart);

        WriteVector3Field(writer, 12.0f, value.PreviewPosition);

        WriteSingleField(writer, 13.0f, value.PreviewPitch);

        WriteSingleField(writer, 14.0f, value.PreviewYaw);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SettingsDefinition ReadSalmon_Levels_Objects_SettingsDefinition(BinaryReader reader)
    {
        var value = new SettingsDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -2.0f:
                    value.Title = reader.ReadString();
                    break;
                case -1.0f:
                    value.AutoSave = reader.ReadBoolean();
                    break;
                case 1.0f:
                    value.GridSize = Clamp(reader.ReadSingle(), 0.02f, 10.0f);
                    break;
                case 2.0f:
                    value.RotationSnapDegrees = Clamp(reader.ReadSingle(), 1.0f, 90.0f);
                    break;
                case 3.0f:
                    value.CameraPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 4.0f:
                    value.CameraPitch = reader.ReadSingle();
                    break;
                case 4.1f:
                    value.CameraYaw = reader.ReadSingle();
                    break;
                case 4.3f:
                    value.ObjectsSpawnAtOrigin = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.Material = reader.ReadString();
                    break;
                case 6.0f:
                    value.BackgroundType = reader.ReadString();
                    break;
                case 7.1f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.2f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.3f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 8.5f:
                    value.FogIntensity = Clamp(reader.ReadInt32(), 0.0f, 20.0f);
                    break;
                case 8.6f:
                    value.PreviewMode = reader.ReadBoolean();
                    break;
                case 9.0f:
                    value.DeathY = Clamp(reader.ReadSingle(), -1000.0f, 1000.0f);
                    break;
                case 9.1f:
                    value.DisplayStyle = reader.ReadBoolean();
                    break;
                case 9.2f:
                    value.AllowWalls = reader.ReadBoolean();
                    break;
                case 9.3f:
                    value.AllowCoyote = reader.ReadBoolean();
                    break;
                case 10.0f:
                    value.PreviewGuide = reader.ReadBoolean();
                    break;
                case 11.0f:
                    value.PreviewStart = reader.ReadBoolean();
                    break;
                case 12.0f:
                    value.PreviewPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 13.0f:
                    value.PreviewPitch = reader.ReadSingle();
                    break;
                case 14.0f:
                    value.PreviewYaw = reader.ReadSingle();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.SettingsDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_SkyColourTriggerObjectDefinition(SkyColourTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteSingleField(writer, 3.0f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 5.0f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteInt32Field(writer, 6.0f, Clamp(value.FogIntensity, 0.0f, 20.0f));

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SkyColourTriggerObjectDefinition ReadSalmon_Levels_Objects_SkyColourTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new SkyColourTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.0f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 6.0f:
                    value.FogIntensity = Clamp(reader.ReadInt32(), 0.0f, 20.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.SkyColourTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_TeleportTriggerObjectDefinition(TeleportTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteObjectReferencesField(writer, 3.0f, value.Trigger);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TeleportTriggerObjectDefinition ReadSalmon_Levels_Objects_TeleportTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new TeleportTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.TeleportTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_TextObjectDefinition(TextObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(12u);

        WriteSingleField(writer, 3.0f, Clamp(value.Width, 0.1f, 999.0f));

        WriteSingleField(writer, 3.1f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 3.2f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 3.3f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.FontSize, 0.1f, 999.0f));

        WriteStringField(writer, 5.0f, value.Text);

        WriteInt32Field(writer, 6.0f, value.CounterID);

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TextObjectDefinition ReadSalmon_Levels_Objects_TextObjectDefinition(BinaryReader reader)
    {
        var value = new TextObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Width = Clamp(reader.ReadSingle(), 0.1f, 999.0f);
                    break;
                case 3.1f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 3.2f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 3.3f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.FontSize = Clamp(reader.ReadSingle(), 0.1f, 999.0f);
                    break;
                case 5.0f:
                    value.Text = reader.ReadString();
                    break;
                case 6.0f:
                    value.CounterID = reader.ReadInt32();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.TextObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_ToggleTriggerObjectDefinition(ToggleTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(4u);

        WriteObjectReferencesField(writer, 3.5f, value.Toggle);

        WriteByteField(writer, 4.0f, (byte)value.Mode);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ToggleTriggerObjectDefinition ReadSalmon_Levels_Objects_ToggleTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new ToggleTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 3.5f:
                    value.Toggle = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Mode = (ToggleMode)reader.ReadByte();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.ToggleTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_TouchTriggerObjectDefinition(TouchTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteObjectReferencesField(writer, 3.5f, value.Trigger);

        WriteSingleField(writer, 4.0f, Clamp(value.Cooldown, -1.0f, 999.0f));

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TouchTriggerObjectDefinition ReadSalmon_Levels_Objects_TouchTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new TouchTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.5f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Cooldown = Clamp(reader.ReadSingle(), -1.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.TouchTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_Wall(Wall value, BinaryWriter writer)
    {
        writer.Write(15u);

        WriteStringField(writer, 2.5f, value.Shape);

        WriteStringField(writer, 3.0f, value.Material);

        WriteBooleanField(writer, 3.5f, value.StableMaterial);

        WriteSingleField(writer, 4.0f, Clamp(value.Damp, 0.0f, 1.0f));

        WriteByteField(writer, 5.0f, (byte)value.Mode);

        WriteBooleanField(writer, 5.5f, value.Deadly);

        WriteSingleField(writer, 6.0f, Clamp(value.BreakVelocity, -1.0f, 999.0f));

        WriteObjectReferencesField(writer, 8.0f, value.Trigger);

        WriteObjectReferencesField(writer, 9.0f, value.OnTouch);

        WriteSingleField(writer, 10.0f, Clamp(value.TouchCooldown, 0.0f, 999.0f));

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static Wall ReadSalmon_Levels_Objects_Wall(BinaryReader reader)
    {
        var value = new Wall();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 2.5f:
                    value.Shape = reader.ReadString();
                    break;
                case 3.0f:
                    value.Material = reader.ReadString();
                    break;
                case 3.5f:
                    value.StableMaterial = reader.ReadBoolean();
                    break;
                case 4.0f:
                    value.Damp = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Mode = (WallMode)reader.ReadByte();
                    break;
                case 5.5f:
                    value.Deadly = reader.ReadBoolean();
                    break;
                case 6.0f:
                    value.BreakVelocity = Clamp(reader.ReadSingle(), -1.0f, 999.0f);
                    break;
                case 8.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 9.0f:
                    value.OnTouch = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                case 10.0f:
                    value.TouchCooldown = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.Wall has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Objects_WinObjectDefinition(WinObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(8u);

        WriteBooleanField(writer, 3.0f, value.Visible);

        WriteBooleanField(writer, 3.5f, value.Audible);

        WriteObjectReferencesField(writer, 4.0f, value.Trigger);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static WinObjectDefinition ReadSalmon_Levels_Objects_WinObjectDefinition(BinaryReader reader)
    {
        var value = new WinObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 3.5f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 4.0f:
                    value.Trigger = ReadSalmon_Levels_Objects_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Objects.WinObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }


}
#endif
