// <auto-generated />
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using Salmon.Levels;

namespace Salmon;

internal static class GeneratedDynamicSerializers
{
    private delegate void WriteDelegate(object value, BinaryWriter writer);
    private delegate object ReadDelegate(BinaryReader reader);

    private static readonly Dictionary<Type, (WriteDelegate Write, ReadDelegate Read)> Serializers = new()
    {
        { typeof(CheckpointObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_CheckpointObjectDefinition((CheckpointObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_CheckpointObjectDefinition(reader))) },
        { typeof(CoinObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_CoinObjectDefinition((CoinObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_CoinObjectDefinition(reader))) },
        { typeof(CounterTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_CounterTriggerObjectDefinition((CounterTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_CounterTriggerObjectDefinition(reader))) },
        { typeof(DeathTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_DeathTriggerObjectDefinition((DeathTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_DeathTriggerObjectDefinition(reader))) },
        { typeof(DelayTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_DelayTriggerObjectDefinition((DelayTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_DelayTriggerObjectDefinition(reader))) },
        { typeof(DestroyTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_DestroyTriggerObjectDefinition((DestroyTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_DestroyTriggerObjectDefinition(reader))) },
        { typeof(FollowTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_FollowTriggerObjectDefinition((FollowTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_FollowTriggerObjectDefinition(reader))) },
        { typeof(Group), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_Group((Group)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_Group(reader))) },
        { typeof(IfTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_IfTriggerObjectDefinition((IfTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_IfTriggerObjectDefinition(reader))) },
        { typeof(LightObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_LightObjectDefinition((LightObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_LightObjectDefinition(reader))) },
        { typeof(MagnetFieldObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_MagnetFieldObjectDefinition((MagnetFieldObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_MagnetFieldObjectDefinition(reader))) },
        { typeof(MagnetPointObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_MagnetPointObjectDefinition((MagnetPointObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_MagnetPointObjectDefinition(reader))) },
        { typeof(MoveTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_MoveTriggerObjectDefinition((MoveTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_MoveTriggerObjectDefinition(reader))) },
        { typeof(ObjectReferences), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_ObjectReferences((ObjectReferences)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_ObjectReferences(reader))) },
        { typeof(RotationTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_RotationTriggerObjectDefinition((RotationTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_RotationTriggerObjectDefinition(reader))) },
        { typeof(SetMaterialTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_SetMaterialTriggerObjectDefinition((SetMaterialTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_SetMaterialTriggerObjectDefinition(reader))) },
        { typeof(SettingsDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_SettingsDefinition((SettingsDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_SettingsDefinition(reader))) },
        { typeof(SkyColourTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_SkyColourTriggerObjectDefinition((SkyColourTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_SkyColourTriggerObjectDefinition(reader))) },
        { typeof(TeleportTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_TeleportTriggerObjectDefinition((TeleportTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_TeleportTriggerObjectDefinition(reader))) },
        { typeof(TextObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_TextObjectDefinition((TextObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_TextObjectDefinition(reader))) },
        { typeof(ToggleTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_ToggleTriggerObjectDefinition((ToggleTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_ToggleTriggerObjectDefinition(reader))) },
        { typeof(TouchTriggerObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_TouchTriggerObjectDefinition((TouchTriggerObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_TouchTriggerObjectDefinition(reader))) },
        { typeof(Wall), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_Wall((Wall)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_Wall(reader))) },
        { typeof(WinObjectDefinition), ((WriteDelegate)(static (value, writer) => WriteSalmon_Levels_WinObjectDefinition((WinObjectDefinition)value, writer)), (ReadDelegate)(static reader => ReadSalmon_Levels_WinObjectDefinition(reader))) },
    };

    public static bool TryWrite(object value, BinaryWriter writer)
    {
        if (value == null || !Serializers.TryGetValue(value.GetType(), out var serializer))
            return false;

        serializer.Write(value, writer);
        return true;
    }

    public static bool TryRead(Type type, BinaryReader reader, out object value)
    {
        if (!Serializers.TryGetValue(type, out var serializer))
        {
            value = null;
            return false;
        }

        value = serializer.Read(reader);
        return true;
    }

    private static byte Clamp(byte value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (byte)min;
        if (!float.IsNaN(max) && value > max) value = (byte)max;
        return value;
    }

    private static sbyte Clamp(sbyte value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (sbyte)min;
        if (!float.IsNaN(max) && value > max) value = (sbyte)max;
        return value;
    }

    private static short Clamp(short value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (short)min;
        if (!float.IsNaN(max) && value > max) value = (short)max;
        return value;
    }

    private static ushort Clamp(ushort value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (ushort)min;
        if (!float.IsNaN(max) && value > max) value = (ushort)max;
        return value;
    }

    private static int Clamp(int value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (int)min;
        if (!float.IsNaN(max) && value > max) value = (int)max;
        return value;
    }

    private static uint Clamp(uint value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (uint)min;
        if (!float.IsNaN(max) && value > max) value = (uint)max;
        return value;
    }

    private static long Clamp(long value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (long)min;
        if (!float.IsNaN(max) && value > max) value = (long)max;
        return value;
    }

    private static ulong Clamp(ulong value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = (ulong)min;
        if (!float.IsNaN(max) && value > max) value = (ulong)max;
        return value;
    }

    private static float Clamp(float value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = min;
        if (!float.IsNaN(max) && value > max) value = max;
        return value;
    }

    private static double Clamp(double value, float min, float max)
    {
        if (!float.IsNaN(min) && value < min) value = min;
        if (!float.IsNaN(max) && value > max) value = max;
        return value;
    }

    private static decimal Clamp(decimal value, float min, float max)
    {
        if (!float.IsNaN(min) && value < (decimal)min) value = (decimal)min;
        if (!float.IsNaN(max) && value > (decimal)max) value = (decimal)max;
        return value;
    }

    private static Vector3 Clamp(Vector3 value, float min, float max)
    {
        if (!float.IsNaN(min) && value.x < min) value.x = min;
        if (!float.IsNaN(max) && value.x > max) value.x = max;
        if (!float.IsNaN(min) && value.y < min) value.y = min;
        if (!float.IsNaN(max) && value.y > max) value.y = max;
        if (!float.IsNaN(min) && value.z < min) value.z = min;
        if (!float.IsNaN(max) && value.z > max) value.z = max;
        return value;
    }


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteBooleanField(BinaryWriter writer, float order, bool value)
    {
        Span<byte> bytes = stackalloc byte[9];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 1u);
        bytes[8] = value ? (byte)1 : (byte)0;
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteByteField(BinaryWriter writer, float order, byte value)
    {
        Span<byte> bytes = stackalloc byte[9];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 1u);
        bytes[8] = value;
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSByteField(BinaryWriter writer, float order, sbyte value)
    {
        Span<byte> bytes = stackalloc byte[9];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 1u);
        bytes[8] = unchecked((byte)value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteInt16Field(BinaryWriter writer, float order, short value)
    {
        Span<byte> bytes = stackalloc byte[10];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 2u);
        BinaryPrimitives.WriteInt16LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteUInt16Field(BinaryWriter writer, float order, ushort value)
    {
        Span<byte> bytes = stackalloc byte[10];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 2u);
        BinaryPrimitives.WriteUInt16LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteInt32Field(BinaryWriter writer, float order, int value)
    {
        Span<byte> bytes = stackalloc byte[12];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 4u);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteUInt32Field(BinaryWriter writer, float order, uint value)
    {
        Span<byte> bytes = stackalloc byte[12];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 4u);
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteInt64Field(BinaryWriter writer, float order, long value)
    {
        Span<byte> bytes = stackalloc byte[16];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 8u);
        BinaryPrimitives.WriteInt64LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteUInt64Field(BinaryWriter writer, float order, ulong value)
    {
        Span<byte> bytes = stackalloc byte[16];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 8u);
        BinaryPrimitives.WriteUInt64LittleEndian(bytes.Slice(8), value);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSingleField(BinaryWriter writer, float order, float value)
    {
        Span<byte> bytes = stackalloc byte[12];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 4u);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(8), BitConverter.SingleToInt32Bits(value));
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteDoubleField(BinaryWriter writer, float order, double value)
    {
        Span<byte> bytes = stackalloc byte[16];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 8u);
        BinaryPrimitives.WriteInt64LittleEndian(bytes.Slice(8), BitConverter.DoubleToInt64Bits(value));
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteDecimalField(BinaryWriter writer, float order, decimal value)
    {
        Span<byte> bytes = stackalloc byte[24];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 16u);
        var bits = decimal.GetBits(value);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(8), bits[0]);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(12), bits[1]);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(16), bits[2]);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(20), bits[3]);
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteDateTimeField(BinaryWriter writer, float order, DateTime value) => WriteInt64Field(writer, order, value.ToBinary());
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteTimeSpanField(BinaryWriter writer, float order, TimeSpan value) => WriteInt64Field(writer, order, value.Ticks);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteVector3Field(BinaryWriter writer, float order, Vector3 value)
    {
        Span<byte> bytes = stackalloc byte[20];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 12u);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(8), BitConverter.SingleToInt32Bits(value.x));
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(12), BitConverter.SingleToInt32Bits(value.y));
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(16), BitConverter.SingleToInt32Bits(value.z));
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteQuaternionField(BinaryWriter writer, float order, Quaternion value)
    {
        Span<byte> bytes = stackalloc byte[24];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), 16u);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(8), BitConverter.SingleToInt32Bits(value.x));
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(12), BitConverter.SingleToInt32Bits(value.y));
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(16), BitConverter.SingleToInt32Bits(value.z));
        BinaryPrimitives.WriteInt32LittleEndian(bytes.Slice(20), BitConverter.SingleToInt32Bits(value.w));
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int Get7BitEncodedIntSize(int value)
    {
        if ((uint)value < 0x80u) return 1;
        if ((uint)value < 0x4000u) return 2;
        if ((uint)value < 0x200000u) return 3;
        if ((uint)value < 0x10000000u) return 4;
        return 5;
    }

    private static void WriteStringField(BinaryWriter writer, float order, string value)
    {
        var byteCount = Encoding.UTF8.GetByteCount(value);
        var serializedLength = Get7BitEncodedIntSize(byteCount) + byteCount;
        Span<byte> header = stackalloc byte[8];
        BinaryPrimitives.WriteInt32LittleEndian(header, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(header.Slice(4), checked((uint)serializedLength));
        writer.BaseStream.Write(header);
        writer.Write(value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteObjectReferencesField(BinaryWriter writer, float order, ObjectReferences value)
    {
        var count = value.IDs.Count;
        if ((uint)count > byte.MaxValue)
            throw new InvalidDataException($"ObjectReferences cannot contain more than {byte.MaxValue} IDs.");
        var nestedLength = 10 + count * sizeof(ulong);
        var totalLength = 8 + nestedLength;
        Span<byte> bytes = stackalloc byte[totalLength];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, BitConverter.SingleToInt32Bits(order));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(4), checked((uint)nestedLength));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(8), 0u);
        bytes[12] = 1;
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.Slice(13), checked((uint)(1 + count * sizeof(ulong))));
        bytes[17] = checked((byte)count);
        var offset = 18;
        foreach (var id in value.IDs)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(bytes.Slice(offset), id);
            offset += sizeof(ulong);
        }
        writer.BaseStream.Write(bytes);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_CheckpointObjectDefinition(CheckpointObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteByteField(writer, 3.0f, (byte)value.Direction);

        WriteBooleanField(writer, 4.0f, value.Visible);

        WriteBooleanField(writer, 4.5f, value.Audible);

        WriteObjectReferencesField(writer, 6.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CheckpointObjectDefinition ReadSalmon_Levels_CheckpointObjectDefinition(BinaryReader reader)
    {
        var value = new CheckpointObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Direction = (CardinalDirection)reader.ReadByte();
                    break;
                case 4.0f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 4.5f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 6.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.CheckpointObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_CoinObjectDefinition(CoinObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(8u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteBooleanField(writer, 2.5f, value.Visible);

        WriteBooleanField(writer, 2.6f, value.Audible);

        WriteObjectReferencesField(writer, 4.0f, value.OnPickup);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CoinObjectDefinition ReadSalmon_Levels_CoinObjectDefinition(BinaryReader reader)
    {
        var value = new CoinObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 2.5f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 2.6f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 3.0f:
                    value.OnPickupID = reader.ReadString();
                    break;
                case 4.0f:
                    value.OnPickup = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.CoinObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_CounterTriggerObjectDefinition(CounterTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, 3.0f, value.Counter);

        WriteByteField(writer, 5.0f, (byte)value.Operator);

        WriteStringField(writer, 6.0f, value.Operand);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CounterTriggerObjectDefinition ReadSalmon_Levels_CounterTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new CounterTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Counter = reader.ReadString();
                    break;
                case 5.0f:
                    value.Operator = (Operator)reader.ReadByte();
                    break;
                case 6.0f:
                    value.Operand = reader.ReadString();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.CounterTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_DeathTriggerObjectDefinition(DeathTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.0f, value.OnRespawn);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DeathTriggerObjectDefinition ReadSalmon_Levels_DeathTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DeathTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.OnRespawn = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.DeathTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_DelayTriggerObjectDefinition(DelayTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.5f, value.Trigger);

        WriteSingleField(writer, 4.0f, Clamp(value.Wait, 0.0f, 999.0f));

        WriteBooleanField(writer, 5.0f, value.RunOnStart);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DelayTriggerObjectDefinition ReadSalmon_Levels_DelayTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DelayTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Wait = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.0f:
                    value.RunOnStart = reader.ReadBoolean();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.DelayTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_DestroyTriggerObjectDefinition(DestroyTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.5f, value.Destroy);

        WriteSingleField(writer, 6.0f, Clamp(value.Wait, 0.0f, 999.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static DestroyTriggerObjectDefinition ReadSalmon_Levels_DestroyTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new DestroyTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.DestroyID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Destroy = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 6.0f:
                    value.Wait = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.DestroyTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_FollowTriggerObjectDefinition(FollowTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteByteField(writer, 3.0f, (byte)value.FollowTarget);

        WriteSingleField(writer, 4.0f, Clamp(value.FollowRate, 0.0f, 1000.0f));

        WriteBooleanField(writer, 4.5f, value.Snap);

        WriteObjectReferencesField(writer, 5.0f, value.Follow);

        WriteBooleanField(writer, 6.0f, value.RunOnStart);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static FollowTriggerObjectDefinition ReadSalmon_Levels_FollowTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new FollowTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.FollowTarget = (FollowTarget)reader.ReadByte();
                    break;
                case 4.0f:
                    value.FollowRate = Clamp(reader.ReadSingle(), 0.0f, 1000.0f);
                    break;
                case 4.5f:
                    value.Snap = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.Follow = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 6.0f:
                    value.RunOnStart = reader.ReadBoolean();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.FollowTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Group(Group value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        writer.Write(true);
        var specialLengthPosition = writer.BaseStream.Position;
        writer.Write(0u);
        var specialStart = writer.BaseStream.Position;
        ((ISpecialSerializable)value).SpecialWrite(writer);
        var specialEnd = writer.BaseStream.Position;
        writer.BaseStream.Position = specialLengthPosition;
        writer.Write(checked((uint)(specialEnd - specialStart)));
        writer.BaseStream.Position = specialEnd;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static Group ReadSalmon_Levels_Group(BinaryReader reader)
    {
        var value = new Group();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Group has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            ((ISpecialSerializable)value).SpecialRead(reader);
            if (reader.BaseStream.Position != specialEnd)
            {
                Debug.LogWarning($"Special read on Salmon.Levels.Group has length {specialLength} but read {reader.BaseStream.Position - (specialEnd - specialLength)} bytes.");
            }
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_IfTriggerObjectDefinition(IfTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, 3.0f, value.Counter);

        WriteInt32Field(writer, 4.0f, value.Operand);

        WriteByteField(writer, 5.0f, (byte)value.Operator);

        WriteObjectReferencesField(writer, 8.0f, value.TrueTrigger);

        WriteObjectReferencesField(writer, 9.0f, value.FalseTrigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static IfTriggerObjectDefinition ReadSalmon_Levels_IfTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new IfTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Counter = reader.ReadString();
                    break;
                case 4.0f:
                    value.Operand = reader.ReadInt32();
                    break;
                case 5.0f:
                    value.Operator = (Comparison)reader.ReadByte();
                    break;
                case 6.0f:
                    value.TrueTriggerID = reader.ReadString();
                    break;
                case 7.0f:
                    value.FalseTriggerID = reader.ReadString();
                    break;
                case 8.0f:
                    value.TrueTrigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 9.0f:
                    value.FalseTrigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.IfTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_LightObjectDefinition(LightObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(9u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 3.0f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 5.0f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteSingleField(writer, 6.0f, Clamp(value.Intensity, 0.0f, 999.0f));

        WriteSingleField(writer, 7.0f, Clamp(value.Radius, 0.0f, 99.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static LightObjectDefinition ReadSalmon_Levels_LightObjectDefinition(BinaryReader reader)
    {
        var value = new LightObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 6.0f:
                    value.Intensity = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 7.0f:
                    value.Radius = Clamp(reader.ReadSingle(), 0.0f, 99.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.LightObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_MagnetFieldObjectDefinition(MagnetFieldObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteSingleField(writer, 3.0f, Clamp(value.Strength, 0.0f, 999.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MagnetFieldObjectDefinition ReadSalmon_Levels_MagnetFieldObjectDefinition(BinaryReader reader)
    {
        var value = new MagnetFieldObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Strength = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.MagnetFieldObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_MagnetPointObjectDefinition(MagnetPointObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 3.0f, Clamp(value.Strength, -999.0f, 999.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Radius, 0.0f, 999.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MagnetPointObjectDefinition ReadSalmon_Levels_MagnetPointObjectDefinition(BinaryReader reader)
    {
        var value = new MagnetPointObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Strength = Clamp(reader.ReadSingle(), -999.0f, 999.0f);
                    break;
                case 4.0f:
                    value.Radius = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.MagnetPointObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_MoveTriggerObjectDefinition(MoveTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(10u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.5f, value.Move);

        WriteByteField(writer, 4.0f, (byte)value.MoveSpeedMode);

        WriteSingleField(writer, 5.0f, Clamp(value.MoveSpeed, 0.0f, 999.0f));

        WriteInt32Field(writer, 5.5f, (int)value.EasingType);

        WriteInt32Field(writer, 5.6f, (int)value.EasingDirection);

        WriteObjectReferencesField(writer, 7.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static MoveTriggerObjectDefinition ReadSalmon_Levels_MoveTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new MoveTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.MoveID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Move = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.MoveSpeedMode = (MoveSpeedMode)reader.ReadByte();
                    break;
                case 5.0f:
                    value.MoveSpeed = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.5f:
                    value.EasingType = (EasingType)reader.ReadInt32();
                    break;
                case 5.6f:
                    value.EasingDirection = (EasingDirection)reader.ReadInt32();
                    break;
                case 6.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 7.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.MoveTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_ObjectReferences(ObjectReferences value, BinaryWriter writer)
    {
        writer.Write(0u);

        writer.Write(true);
        var specialLengthPosition = writer.BaseStream.Position;
        writer.Write(0u);
        var specialStart = writer.BaseStream.Position;
        ((ISpecialSerializable)value).SpecialWrite(writer);
        var specialEnd = writer.BaseStream.Position;
        writer.BaseStream.Position = specialLengthPosition;
        writer.Write(checked((uint)(specialEnd - specialStart)));
        writer.BaseStream.Position = specialEnd;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ObjectReferences ReadSalmon_Levels_ObjectReferences(BinaryReader reader)
    {
        var value = new ObjectReferences();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.ObjectReferences has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            ((ISpecialSerializable)value).SpecialRead(reader);
            if (reader.BaseStream.Position != specialEnd)
            {
                Debug.LogWarning($"Special read on Salmon.Levels.ObjectReferences has length {specialLength} but read {reader.BaseStream.Position - (specialEnd - specialLength)} bytes.");
            }
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_RotationTriggerObjectDefinition(RotationTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(10u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.5f, value.Rotate);

        WriteByteField(writer, 4.0f, (byte)value.RotationSpeedMode);

        WriteSingleField(writer, 5.0f, Clamp(value.RotationSpeed, 0.0f, 999.0f));

        WriteInt32Field(writer, 5.5f, (int)value.EasingType);

        WriteInt32Field(writer, 5.6f, (int)value.EasingDirection);

        WriteObjectReferencesField(writer, 7.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static RotationTriggerObjectDefinition ReadSalmon_Levels_RotationTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new RotationTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.RotateID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Rotate = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.RotationSpeedMode = (RotationSpeedMode)reader.ReadByte();
                    break;
                case 5.0f:
                    value.RotationSpeed = Clamp(reader.ReadSingle(), 0.0f, 999.0f);
                    break;
                case 5.5f:
                    value.EasingType = (EasingType)reader.ReadInt32();
                    break;
                case 5.6f:
                    value.EasingDirection = (EasingDirection)reader.ReadInt32();
                    break;
                case 6.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 7.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.RotationTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_SetMaterialTriggerObjectDefinition(SetMaterialTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteStringField(writer, 3.0f, value.Material);

        WriteObjectReferencesField(writer, 5.0f, value.Wall);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SetMaterialTriggerObjectDefinition ReadSalmon_Levels_SetMaterialTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new SetMaterialTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Material = reader.ReadString();
                    break;
                case 4.0f:
                    value.WallID = reader.ReadString();
                    break;
                case 5.0f:
                    value.Wall = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.SetMaterialTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_SettingsDefinition(SettingsDefinition value, BinaryWriter writer)
    {
        writer.Write(19u);

        WriteBooleanField(writer, -1.0f, value.AutoSave);

        WriteSingleField(writer, 1.0f, Clamp(value.GridSize, 0.01f, 10.0f));

        WriteSingleField(writer, 2.0f, Clamp(value.RotationSnapDegrees, 1.0f, 90.0f));

        WriteVector3Field(writer, 3.0f, value.CameraPosition);

        WriteSingleField(writer, 4.0f, value.CameraPitch);

        WriteSingleField(writer, 4.1f, value.CameraYaw);

        WriteBooleanField(writer, 4.3f, value.ObjectsSpawnAtOrigin);

        WriteStringField(writer, 5.0f, value.Material);

        WriteStringField(writer, 6.0f, value.BackgroundType);

        WriteSingleField(writer, 7.1f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 7.2f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 7.3f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteInt32Field(writer, 8.5f, Clamp(value.FogIntensity, 0.0f, 20.0f));

        WriteSingleField(writer, 9.0f, Clamp(value.DeathY, -1000.0f, 1000.0f));

        WriteBooleanField(writer, 10.0f, value.PreviewGuide);

        WriteBooleanField(writer, 11.0f, value.PreviewStart);

        WriteVector3Field(writer, 12.0f, value.PreviewPosition);

        WriteSingleField(writer, 13.0f, value.PreviewPitch);

        WriteSingleField(writer, 14.0f, value.PreviewYaw);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SettingsDefinition ReadSalmon_Levels_SettingsDefinition(BinaryReader reader)
    {
        var value = new SettingsDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -2.0f:
                    value.Title = reader.ReadString();
                    break;
                case -1.0f:
                    value.AutoSave = reader.ReadBoolean();
                    break;
                case 1.0f:
                    value.GridSize = Clamp(reader.ReadSingle(), 0.01f, 10.0f);
                    break;
                case 2.0f:
                    value.RotationSnapDegrees = Clamp(reader.ReadSingle(), 1.0f, 90.0f);
                    break;
                case 3.0f:
                    value.CameraPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 4.0f:
                    value.CameraPitch = reader.ReadSingle();
                    break;
                case 4.1f:
                    value.CameraYaw = reader.ReadSingle();
                    break;
                case 4.3f:
                    value.ObjectsSpawnAtOrigin = reader.ReadBoolean();
                    break;
                case 5.0f:
                    value.Material = reader.ReadString();
                    break;
                case 6.0f:
                    value.BackgroundType = reader.ReadString();
                    break;
                case 7.1f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.2f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 7.3f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 8.0f:
                    value._FogIntensity = reader.ReadString();
                    break;
                case 8.5f:
                    value.FogIntensity = Clamp(reader.ReadInt32(), 0.0f, 20.0f);
                    break;
                case 9.0f:
                    value.DeathY = Clamp(reader.ReadSingle(), -1000.0f, 1000.0f);
                    break;
                case 10.0f:
                    value.PreviewGuide = reader.ReadBoolean();
                    break;
                case 11.0f:
                    value.PreviewStart = reader.ReadBoolean();
                    break;
                case 12.0f:
                    value.PreviewPosition = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 13.0f:
                    value.PreviewPitch = reader.ReadSingle();
                    break;
                case 14.0f:
                    value.PreviewYaw = reader.ReadSingle();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.SettingsDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_SkyColourTriggerObjectDefinition(SkyColourTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(8u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 3.0f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 5.0f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteInt32Field(writer, 6.0f, Clamp(value.FogIntensity, 0.0f, 20.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static SkyColourTriggerObjectDefinition ReadSalmon_Levels_SkyColourTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new SkyColourTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 6.0f:
                    value.FogIntensity = Clamp(reader.ReadInt32(), 0.0f, 20.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.SkyColourTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_TeleportTriggerObjectDefinition(TeleportTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(5u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TeleportTriggerObjectDefinition ReadSalmon_Levels_TeleportTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new TeleportTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.TeleportTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_TextObjectDefinition(TextObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(11u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteSingleField(writer, 3.0f, Clamp(value.Width, 0.1f, 999.0f));

        WriteSingleField(writer, 3.1f, Clamp(value.Red, 0.0f, 1.0f));

        WriteSingleField(writer, 3.2f, Clamp(value.Green, 0.0f, 1.0f));

        WriteSingleField(writer, 3.3f, Clamp(value.Blue, 0.0f, 1.0f));

        WriteSingleField(writer, 4.0f, Clamp(value.FontSize, 0.1f, 999.0f));

        WriteStringField(writer, 5.0f, value.Text);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TextObjectDefinition ReadSalmon_Levels_TextObjectDefinition(BinaryReader reader)
    {
        var value = new TextObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Width = Clamp(reader.ReadSingle(), 0.1f, 999.0f);
                    break;
                case 3.1f:
                    value.Red = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 3.2f:
                    value.Green = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 3.3f:
                    value.Blue = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 4.0f:
                    value.FontSize = Clamp(reader.ReadSingle(), 0.1f, 999.0f);
                    break;
                case 5.0f:
                    value.Text = reader.ReadString();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.TextObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_ToggleTriggerObjectDefinition(ToggleTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(6u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteObjectReferencesField(writer, 3.5f, value.Toggle);

        WriteByteField(writer, 4.0f, (byte)value.Mode);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ToggleTriggerObjectDefinition ReadSalmon_Levels_ToggleTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new ToggleTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 3.0f:
                    value.ToggleID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Toggle = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Mode = (ToggleMode)reader.ReadByte();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.ToggleTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_TouchTriggerObjectDefinition(TouchTriggerObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(7u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteObjectReferencesField(writer, 3.5f, value.Trigger);

        WriteSingleField(writer, 4.0f, Clamp(value.Cooldown, -1.0f, 999.0f));

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static TouchTriggerObjectDefinition ReadSalmon_Levels_TouchTriggerObjectDefinition(BinaryReader reader)
    {
        var value = new TouchTriggerObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 3.5f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                case 4.0f:
                    value.Cooldown = Clamp(reader.ReadSingle(), -1.0f, 999.0f);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.TouchTriggerObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_Wall(Wall value, BinaryWriter writer)
    {
        writer.Write(12u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteVector3Field(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteStringField(writer, 2.5f, value.Shape);

        WriteStringField(writer, 3.0f, value.Material);

        WriteSingleField(writer, 4.0f, Clamp(value.Damp, 0.0f, 1.0f));

        WriteByteField(writer, 5.0f, (byte)value.Mode);

        WriteBooleanField(writer, 5.5f, value.Deadly);

        WriteSingleField(writer, 6.0f, Clamp(value.BreakVelocity, -1.0f, 999.0f));

        WriteObjectReferencesField(writer, 8.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static Wall ReadSalmon_Levels_Wall(BinaryReader reader)
    {
        var value = new Wall();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle()), 0.05f, float.NaN);
                    break;
                case 2.5f:
                    value.Shape = reader.ReadString();
                    break;
                case 3.0f:
                    value.Material = reader.ReadString();
                    break;
                case 4.0f:
                    value.Damp = Clamp(reader.ReadSingle(), 0.0f, 1.0f);
                    break;
                case 5.0f:
                    value.Mode = (WallMode)reader.ReadByte();
                    break;
                case 5.5f:
                    value.Deadly = reader.ReadBoolean();
                    break;
                case 6.0f:
                    value.BreakVelocity = Clamp(reader.ReadSingle(), -1.0f, 999.0f);
                    break;
                case 7.0f:
                    value.TriggerID = reader.ReadString();
                    break;
                case 8.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.Wall has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteSalmon_Levels_WinObjectDefinition(WinObjectDefinition value, BinaryWriter writer)
    {
        writer.Write(8u);

        WriteStringField(writer, -999.0f, value.Name);

        WriteUInt64Field(writer, -1.0f, value.ID);

        WriteVector3Field(writer, 0.0f, value.Position);

        WriteVector3Field(writer, 1.0f, value.Rotation);

        WriteSingleField(writer, 2.0f, Clamp(value.Scale, 0.05f, float.NaN));

        WriteBooleanField(writer, 3.0f, value.Visible);

        WriteBooleanField(writer, 3.5f, value.Audible);

        WriteObjectReferencesField(writer, 4.0f, value.Trigger);

        writer.Write(false);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static WinObjectDefinition ReadSalmon_Levels_WinObjectDefinition(BinaryReader reader)
    {
        var value = new WinObjectDefinition();
        var count = checked((ushort)reader.ReadUInt32());
        for (var fieldIndex = 0u; fieldIndex < count; fieldIndex++)
        {
            var order = reader.ReadSingle();
            var length = reader.ReadUInt32();
            var fieldEnd = checked(reader.BaseStream.Position + length);
            var handled = true;

            switch (order)
            {
                case -999.0f:
                    value.Name = reader.ReadString();
                    break;
                case -1.0f:
                    value.ID = reader.ReadUInt64();
                    break;
                case 0.0f:
                    value.Position = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 1.0f:
                    value.Rotation = new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
                    break;
                case 2.0f:
                    value.Scale = Clamp(reader.ReadSingle(), 0.05f, float.NaN);
                    break;
                case 3.0f:
                    value.Visible = reader.ReadBoolean();
                    break;
                case 3.5f:
                    value.Audible = reader.ReadBoolean();
                    break;
                case 4.0f:
                    value.Trigger = ReadSalmon_Levels_ObjectReferences(reader);
                    break;
                default:
                    handled = false;
                    break;
            }

            if (handled && reader.BaseStream.Position != fieldEnd)
            {
                Debug.LogWarning($"Field {order} on Salmon.Levels.WinObjectDefinition has length {length} but read {reader.BaseStream.Position - (fieldEnd - length)} bytes.");
            }

            reader.BaseStream.Position = fieldEnd;
        }

        if (reader.ReadBoolean())
        {
            var specialLength = reader.ReadUInt32();
            var specialEnd = checked(reader.BaseStream.Position + specialLength);
            reader.BaseStream.Position = specialEnd;
        }

        return value;
    }


}
