<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>SalmonFile</PackageId>
    <Version>22.0.0</Version>
    <Authors>SeaSharpy</Authors>
    <Description>The .salmon file format library for SALMON levels.</Description>
    <PackageTags>salmon level file format serialization</PackageTags>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright (c) 2026 SeaSharpy</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Update="LICENSE.md" Pack="true" PackagePath="\" />
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
