#if !DEMO_APP
using System.Diagnostics;

namespace Salmon.Levels.Sections;

/// <summary>Stores the level object tree and editor selection state.</summary>
public sealed class ObjectsSection : LevelSection
{
    /// <summary>The root of the level object hierarchy.</summary>
    [InspectorField("Root", Order = 1)]
    public Group Root = new();
    /// <summary>The identifier of the group currently open in the editor.</summary>
    [InspectorField("Group ID", Order = 2)]
    public ulong GroupID = 0;
    /// <summary>The identifiers of the objects selected in the editor.</summary>
    [InspectorField("Selected IDs", Order = 3)]
    public ulong[] SelectedIDs = [];
    
    [InspectorField("Counters", Order = 4)]
    internal Dictionary<string, int> Counters = [];
    /// <summary>The errors generated by various parts of the level.</summary>
    public readonly List<string> Errors = [];
    /// <summary>The warnings generated by various parts of the level.</summary>
    public readonly List<string> Warnings = [];

    internal override void Write(BinaryWriter writer)
    {
        Compile();
        DynamicSerializer.Serialize(this, writer);
    }
    internal void Compile()
    {
        Counters.Clear();
        var counterIndex = 0;
        var objects = Root.Recurse().ToArray();
        foreach (var obj in objects)
            if (obj is CounterTriggerObjectDefinition counterTrigger)
            {
                counterTrigger.Counter ??= "";
                if (!Counters.ContainsKey(counterTrigger.Counter))
                    Counters[counterTrigger.Counter] = counterIndex++;
            }
        Errors.Clear();
        Warnings.Clear();
        var touchTriggerWarned = 0;
        foreach (var obj in objects)
            switch (obj)
            {
                case TextObjectDefinition text:
                    text.CounterID = -1;
                    if (text.Text?.StartsWith("$", StringComparison.Ordinal) == true)
                        text.CounterID = ResolveCounterID(ObjectReferences.GetDisplayPath(obj.ID, Root), text.Text.Substring(1));
                    break;
                case CounterTriggerObjectDefinition counterTrigger:
                    var counterPath = ObjectReferences.GetDisplayPath(obj.ID, Root);
                    counterTrigger.CounterID = ResolveCounterID(counterPath, counterTrigger.Counter);
                    counterTrigger.CounterIDs = CompileExpression(counterPath, counterTrigger.Operand ?? "");
                    break;
                case IfTriggerObjectDefinition ifTrigger:
                    var ifPath = ObjectReferences.GetDisplayPath(obj.ID, Root);
                    ifTrigger.CounterIDs = CompileExpression(ifPath, ifTrigger.Expression ?? "");
                    break;
                case Wall wall:
                    var wallPath = ObjectReferences.GetDisplayPath(obj.ID, Root);
                    if (wall.Mode == WallMode.Visuals && wall.OnTouch.IDs.Count > 0)
                        Warnings.Add($"Wall {wallPath} has On Touch set in Visuals mode. Use Trigger mode instead.");
                    if (wall.Mode == WallMode.Visuals && (wall.Trigger.IDs.Count > 0 || wall.BreakVelocity > -1f))
                        Warnings.Add($"Wall {wallPath} has On Break set or Break Velocity enabled in Visuals mode. Use a collision mode instead.");
                    if (wall.Trigger.IDs.Count > 0 && wall.BreakVelocity < 0f)
                        Warnings.Add($"Wall {wallPath} has On Break set while Break Velocity is disabled.");
                    break;
                case TouchTriggerObjectDefinition touchTrigger:
                    if (touchTriggerWarned++ == 0)
                        Warnings.Add("Touch triggers are soon to be replaced by just walls with On Touch.");
                    break;
            }
    }
    private int[] CompileExpression(string obj, string expression)
    {
        var errorStart = Errors.Count;
        var warningStart = Warnings.Count;
        var parser = new ExpressionParser(expression, Counters, Errors, Warnings);
        parser.Parse();
        for (var i = errorStart; i < Errors.Count; i++)
            Errors[i] = $"{obj}: {Errors[i]}";
        for (var i = warningStart; i < Warnings.Count; i++)
            Warnings[i] = $"{obj}: {Warnings[i]}";
        return parser.CounterIDs;
    }
    private int ResolveCounterID(string obj, string counter)
    {
        if (string.IsNullOrEmpty(counter))
        {
            Warnings.Add($"Counter on {obj} is empty.");
            return Counters.TryGetValue(counter ?? "", out var emptyCounterID) ? emptyCounterID : -1;
        }
        for (var i = 0; i < counter.Length; i++)
            if (!char.IsLetterOrDigit(counter[i]) && counter[i] != '_')
            {
                Warnings.Add($"Counter on {obj} contains invalid character '{counter[i]}'.");
                return Counters.TryGetValue(counter, out var invalidCounterID) ? invalidCounterID : -1;
            }
        if (!Counters.TryGetValue(counter, out var counterID))
        {
            Warnings.Add($"{obj} references nonexistent counter '{counter}'.");
            return -1;
        }
        return counterID;
    }
    
    internal override void Read(BinaryReader reader)
    {
        if (Version < 22)
        {
            Root = (Group)DynamicSerializer.Deserialize(typeof(Group), reader);
            GroupID = reader.ReadUInt64();
            var count = reader.ReadInt32();
            SelectedIDs = new ulong[count];
            for (var i = 0; i < count; i++)
                SelectedIDs[i] = reader.ReadUInt64();
        }
        else DynamicSerializer.Deserialize(typeof(ObjectsSection), this, reader);
        if (Version < 22)
            foreach (var obj in Root.Recurse())
                if (obj is IfTriggerObjectDefinition ifTrigger)
                {
                    var comparison = ifTrigger.Operator switch
                    {
                        Comparison.Equal => "==",
                        Comparison.NotEqual => "!=",
                        Comparison.Greater => ">",
                        Comparison.Less => "<",
                        Comparison.GreaterOrEqual => ">=",
                        _ => "<="
                    };
                    ifTrigger.Expression = $"{ifTrigger.Operand} {comparison} ${ifTrigger.Counter}";
                }
        if (Version < 22)
            Compile();
    }
    /// <inheritdoc/>
    public override void Normalize()
    {
        EnsureUniqueObjectNames();
    }

    /// <summary>Ensures every group contains non-empty, case-insensitively unique child names.</summary>
    public void EnsureUniqueObjectNames()
    {
        foreach (var obj in Root.Recurse())
            if (obj is Group currentGroup)
                EnsureUniqueObjectNames(currentGroup);
    }

    /// <summary>Ensures a group's children have non-empty, case-insensitively unique names.</summary>
    /// <param name="group">The group to normalize.</param>
    public static void EnsureUniqueObjectNames(Group group)
    {
        var allocator = new ObjectNameAllocator(group.Objects.Count);

        foreach (var levelObject in group.Objects)
        {
            var name = levelObject.Name;

            if (string.IsNullOrWhiteSpace(name) || name == "Unknown")
                name = levelObject.GetDisplayName();

            levelObject.Name = allocator.Add(name);
        }
    }

    /// <summary>Allocates a unique name among a list of sibling objects.</summary>
    /// <param name="name">The preferred name.</param>
    /// <param name="siblings">The sibling objects whose names are reserved.</param>
    /// <param name="self">An optional object to exclude from the reserved names.</param>
    /// <returns>The original name or a numbered unique variant.</returns>
    public static string GetUniqueObjectName(
        string name,
        List<ObjectDefinition> siblings,
        ObjectDefinition self = null)
    {
        var allocator = new ObjectNameAllocator(siblings.Count);

        for (var i = 0; i < siblings.Count; i++)
        {
            var sibling = siblings[i];

            if (sibling != null && sibling != self)
                allocator.Reserve(sibling.Name);
        }

        return allocator.Add(name);
    }
    private sealed class ObjectNameAllocator
    {
        private readonly HashSet<string> UsedNames;
        private readonly Dictionary<string, int> NextNumbers;

        public ObjectNameAllocator(int capacity)
        {
            UsedNames = new HashSet<string>(
                capacity,
                StringComparer.OrdinalIgnoreCase
            );

            NextNumbers = new Dictionary<string, int>(
                StringComparer.OrdinalIgnoreCase
            );
        }

        public void Reserve(string name)
        {
            UsedNames.Add(name);
        }

        public string Add(string name)
        {
            if (UsedNames.Add(name))
                return name;

            SplitTrailingNumber(
                name,
                out var baseName,
                out var nextNumber
            );

            if (NextNumbers.TryGetValue(name, out var cachedNumber) &&
                cachedNumber > nextNumber)
            {
                nextNumber = cachedNumber;
            }

            while (true)
            {
                var candidate = $"{baseName} {nextNumber}";
                nextNumber++;

                if (!UsedNames.Add(candidate))
                    continue;

                NextNumbers[name] = nextNumber;
                return candidate;
            }
        }
    }

    private static void SplitTrailingNumber(
        string name,
        out string baseName,
        out int nextNumber)
    {
        var digitStart = name.Length;

        while (digitStart > 0 &&
               char.IsDigit(name[digitStart - 1]))
        {
            digitStart--;
        }

        if (digitStart == name.Length)
        {
            baseName = name;
            nextNumber = 2;
            return;
        }

        baseName = name.Substring(0, digitStart).TrimEnd();

        if (baseName.Length == 0 ||
            !int.TryParse(name.Substring(digitStart), out var number) ||
            number == int.MaxValue)
        {
            baseName = name;
            nextNumber = 2;
            return;
        }

        nextNumber = number + 1;
    }
}
#endif
